Try to set a global value for the bc test data location
org.bouncycastle.openpgp.test.DSA2Test > testK1024H512 FAILED
    java.io.FileNotFoundException: /home/parallels/development/spongycastle/pg/core/src/test/data/openpgp/dsa/keys/DSA-1024-160.pub (No such file or directory)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:97)
        at org.bouncycastle.openpgp.test.DSA2Test.loadPublicKey(DSA2Test.java:249)
        at org.bouncycastle.openpgp.test.DSA2Test.doSigVerifyTest(DSA2Test.java:209)
        at org.bouncycastle.openpgp.test.DSA2Test.testK1024H512(DSA2Test.java:73)
> Building > :pg:test > 23 tests completed, 18 failed^Cparallels@ubuntu:~/development/spongycastle$
parallels@ubuntu:~/development/spongycastle$
parallels@ubuntu:~/development/spongycastle$ ls /home/parallels/development/spongycastle/pg/core/src/test/data/openpgp/dsa/keys/DSA-1024-160.pub
ls: cannot access /home/parallels/development/spongycastle/pg/core/src/test/data/openpgp/dsa/keys/DSA-1024-160.pub: No such file or directory
parallels@ubuntu:~/development/spongycastle$ find -name DSA-1024-160.pub
./core/src/test/data/openpgp/dsa/keys/DSA-1024-160.pub
parallels@ubuntu:~/development/spongycastle$ pwd
/home/parallels/development/spongycastle

Conflicts:
	build.gradle